# Generated by Django 5.2.7 on 2025-10-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localisation', '0001_initial'),
        ('utilisateur', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('Visible', 'Visible'), ('Masqué', 'Masqué'), ('Supprimé', 'Supprimé')], default='Visible', max_length=10)),
                ('auteurRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
                ('parentRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='interaction.commentaire')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeContribution', models.CharField(choices=[('Ajout_Arret', 'Ajout Arret'), ('Modification_Trajet', 'Modification Trajet'), ('Ajout_Bus', 'Ajout Bus'), ('Signalement_Erreur', 'Signalement Erreur')], max_length=20)),
                ('details', models.TextField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Rejetée', 'Rejetée')], default='En attente', max_length=20)),
                ('dateSoumission', models.DateTimeField(auto_now_add=True)),
                ('dateValidation', models.DateTimeField(blank=True, null=True)),
                ('utilisateurRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriqueRecherche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRecherche', models.DateTimeField(auto_now_add=True)),
                ('resultat', models.TextField(blank=True, null=True)),
                ('arrivee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherche_arrivee', to='localisation.arret')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherche_depart', to='localisation.arret')),
                ('userRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilisateur.utilisateur')),
            ],
        ),
    ]
