# Generated by Django 5.2.7 on 2025-11-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVille', models.CharField(max_length=100)),
                ('codePostal', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomQuartier', models.CharField(max_length=100)),
                ('villeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='localisation.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArret', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('quartier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='localisation.quartier')),
                ('villeRef', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='localisation.ville')),
            ],
            options={
                'db_table': 'localisation_arret',
            },
        ),
    ]
