# Generated by Django 5.2.7 on 2025-10-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomQuartier', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomVille', models.CharField(max_length=255)),
                ('codePostal', models.CharField(max_length=20)),
                ('pays', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Arret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomArret', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('quartierRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.quartier')),
            ],
        ),
        migrations.AddField(
            model_name='quartier',
            name='villeRef',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.ville'),
        ),
    ]
