# Generated by Django 5.2.7 on 2025-11-26 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('role', models.CharField(choices=[('user', 'Utilisateur'), ('admin', 'Administrateur')], default='user', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('reputation', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'utilisateur_profile',
            },
        ),
    ]
