# Generated by Django 5.2.7 on 2025-11-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroBus', models.CharField(max_length=50)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='Actif', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('frais', models.DecimalField(decimal_places=2, default=600, max_digits=10)),
                ('primus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_depart', to='localisation.arret')),
                ('terminus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_arrivee', to='localisation.arret')),
                ('villeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.ville')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Bus',
                'ordering': ['numeroBus'],
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTrajet', models.CharField(choices=[('Aller', 'Aller'), ('Retour', 'Retour')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='transport.bus')),
            ],
            options={
                'verbose_name': 'Trajet',
                'verbose_name_plural': 'Trajets',
            },
        ),
        migrations.CreateModel(
            name='TrajetArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordrePassage', models.IntegerField()),
                ('direction', models.CharField(choices=[('Aller', 'Aller'), ('Retour', 'Retour'), ('AllerRetour', 'AllerRetour')], max_length=12)),
                ('arretRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.arret')),
                ('trajetRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrets', to='transport.trajet')),
            ],
            options={
                'verbose_name': 'Trajet Arrêt',
                'verbose_name_plural': 'Trajets Arrêts',
                'ordering': ['ordrePassage'],
                'unique_together': {('trajetRef', 'arretRef', 'ordrePassage')},
            },
        ),
    ]
