# Generated by Django 5.2.7 on 2025-10-30 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroBus', models.CharField(max_length=50)),
                ('status', models.CharField(default='Actif', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('primus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_depart', to='localisation.arret')),
                ('terminus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_arrivee', to='localisation.arret')),
                ('villeRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.ville')),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTrajet', models.CharField(choices=[('Aller', 'Aller'), ('Retour', 'Retour')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('busRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.bus')),
            ],
        ),
        migrations.CreateModel(
            name='TrajetArret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordrePassage', models.IntegerField()),
                ('direction', models.CharField(choices=[('Aller', 'Aller'), ('Retour', 'Retour'), ('AllerRetour', 'AllerRetour')], max_length=12)),
                ('arretRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='localisation.arret')),
                ('trajetRef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.trajet')),
            ],
        ),
    ]
